/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <Bootloadable_1.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_MBX.h>
#include <CapSense_TunerHelper.h>
#include <CapSense_PVT.h>
#include <CapSense_IP.h>
#include <SCB_1.h>
#include <SCB_1_PINS.h>
#include <SCB_1_PVT.h>
#include <SCB_1_EZI2C.h>
#include <SCB_1_EZI2C_PVT.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <CapSense_SampleClk.h>
#include <CapSense_Sns_aliases.h>
#include <CapSense_SenseClk.h>
#include <SCB_1_sda.h>
#include <SCB_1_sda_aliases.h>
#include <SCB_1_scl.h>
#include <SCB_1_scl_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

